export const uiText = {
  app: {
    title: "Auto Mosaic",
    menu: "File",
    newProject: "新規プロジェクト",
    openProject: "プロジェクトを開く",
    saveProject: "保存",
    saveProjectAs: "名前を付けて保存",
    backendReady: "バックエンド準備完了",
    backendNeedsSetup: "初期セットアップが必要",
  },
  actions: {
    openVideo: "動画を開く",
    setup: "初期環境セットアップ",
    fetchModels: "不足モデル取得",
    detect: "AI自動検出",
    export: "書き出し",
    cancel: "中断",
    recheck: "再確認",
    checking: "確認中...",
  },
  activity: {
    idle: "待機中です。",
    notice: "長時間処理の進捗は共通 Job Panel に表示されます。",
    ready: "初期環境の確認が完了しました。",
    setupRecommended: "初期環境に不足があります。セットアップを実行してください。",
    doctorFailed: "環境確認に失敗しました。",
    newProjectReady: "新しいプロジェクトを作成しました。",
    projectLoaded: "プロジェクトを読み込みました。",
    projectSaved: "プロジェクトを保存しました。",
    videoReady: "動画を読み込みました。",
    detectStarted: "AI自動検出を開始しました。",
    detectCompleted: "AI自動検出が完了しました。",
    exportStarted: "書き出しを開始しました。",
    exportCompleted: "書き出しが完了しました。",
    exportFailed: "書き出しに失敗しました。",
    savingBeforeEdit: "編集の前にプロジェクトを保存しています...",
    savingBeforeExport: "書き出しの前にプロジェクトを保存しています...",
    jobStarted: (jobKind: string) => `${jobKind} を開始しました。`,
  },
  panels: {
    project: "プロジェクト",
    models: "モデル状態",
    environment: "環境",
    detect: "検出ジョブ",
    export: "書き出しジョブ",
    timeline: "タイムライン",
    trackDetail: "トラック詳細",
    keyframeDetail: "キーフレーム詳細",
  },
  project: {
    untitledName: "Untitled Project",
    name: "名前",
    path: "パス",
    tracks: "トラック数",
    state: "状態",
    none: "なし",
    unsaved: "未保存",
    dirty: "未保存の変更あり",
    saved: "保存済み",
  },
  models: {
    ready: "利用可能",
    missing: "不足",
    empty: "必要モデル情報はまだ取得されていません。",
  },
  preview: {
    emptyTitle: "動画を開いてプレビューを開始",
    emptyHint: "日本語パスの動画でも UTF-8 契約を維持したまま読み込みます。",
    frames: "フレーム数",
    sourcePath: "ソース",
  },
  detect: {
    idle: "検出ジョブはありません。",
  },
  export: {
    idle: "書き出しジョブはありません。",
    preparing: "書き出しを準備中です。",
  },
  timeline: {
    empty: "トラックはまだありません。",
  },
  states: {
    ready: "準備完了",
    missing: "不足",
    cuda: "CUDA 利用可",
    cpuFallback: "CPU fallback",
  },
  jobs: {
    panelTitle: "ジョブ進捗",
    stage: "ステージ",
    progress: "進捗",
    indeterminate: "進捗率取得中",
    cancelling: "中断要求を送信しました。",
    detectTitle: "AI自動検出",
    exportTitle: "動画を書き出し中",
  },
  jobStages: {
    queued: "待機中",
    starting: "開始中",
    cancelling: "中断中",
    cancelled: "中断済み",
    completed: "完了",
    failed: "失敗",
    runtime_dirs: "書き込み先を確認中",
    doctor: "環境確認中",
    ffmpeg: "ffmpeg / ffprobe を確認中",
    gpu_probe: "GPU を確認中",
    model_check: "必須モデルを確認中",
    model_fetch: "不足モデルを取得中",
    downloading: "ダウンロード中",
    verifying: "検証中",
    metadata_probe: "動画メタ情報を取得中",
    preview_probe: "先頭フレームを準備中",
    preview_init: "プレビューを初期化中",
    preparing: "準備中",
    loading_model: "検出モデルを読み込み中",
    probing_video: "動画を確認中",
    sampling_frames: "フレームをサンプリング中",
    running_inference: "推論実行中",
    building_tracks: "トラックを構築中",
    rendering_frames: "フレームを書き出し中",
    muxing_audio: "音声を結合中",
    finalizing: "完了処理中",
  },
  errors: {
    saveBeforeExport: "書き出しの前にプロジェクトを保存してください。",
  },
} as const;
